"""Career planning agent interface."""

from dotenv import load_dotenv

load_dotenv()

from services.career_coach import generate_career_roadmap


def plan_career_path(parsed_resume, target_role, timeline_months, focus_area, industries):
    """Return a roadmap generated by the career coach service."""
    try:
        return generate_career_roadmap(parsed_resume, target_role, timeline_months, focus_area, industries)
    except Exception as exc:
        return f"Unable to generate roadmap right now: {exc}"
