[server]
port = 8501
headless = true
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = true

[theme]
primaryColor = "#667eea"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#e2e8f0"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
